version: "3.8"
services:
  ceph-spdk:
    image: ceph/spdk-ubi9
    profiles:
      - build
    build:
      context: spdk/
      dockerfile: ../Dockerfile.spdk
      target: ceph-spdk
      args:
        SPDK_VERSION: v23.01
        PKGDEP_ARGS: --rbd
        CONFIGURE_ARGS: >-
          --with-rbd
          --disable-tests
          --disable-unit-tests
          --disable-examples
  ceph-cluster:
    image: ceph-cluster
    container_name: ceph-cluster
    build:
      context: .
      dockerfile: Dockerfile.ceph
    environment:
      VSTART_ARGS: >-
        --without-dashboard
        --memstore
      TOUCHFILE: /tmp/ceph-cluster.touch
    entrypoint: |
      sh -c './vstart.sh --new $$VSTART_ARGS &&
      ceph osd pool create rbd &&
      sleep infinity'
    healthcheck:
      test: ceph osd pool stats rbd
      start_period: 5s
      interval: 5s
    volumes:
      - ceph-conf:/etc/ceph
  ceph-nvmeof-base:
    image: ceph-nvmeof
    build:
      context: .
      target: ceph-nvmeof
    volumes:
      # sudo bash -c 'echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
      # https://spdk.io/doc/containers.html
      # TODO: Pending of https://github.com/spdk/spdk/issues/2973
      - /dev/hugepages:/dev/hugepages
      - ceph-conf:/etc/ceph:ro
    cap_add:
      - SYS_ADMIN
      - CAP_SYS_NICE
  ceph-nvmeof:
    extends:
      service: ceph-nvmeof-base
    depends_on:
      ceph-cluster:
        condition: service_healthy
    ports:
      # Gateway RPC see addr/port in ceph-nvmeof.conf
      - 0.0.0.0:5500:5500

  ceph-nvmeof-pytest-base:
    # Run tests code in current dir
    extends:
      service: ceph-nvmeof-base
    volumes:
      - ./tests:/src/tests

  ceph-nvmeof-pytest-cli:
    extends:
      service: ceph-nvmeof-pytest-base
    entrypoint: |
      python3 -m pytest tests/test_cli.py

  ceph-nvmeof-pytest-multi-gateway:
    extends:
      service: ceph-nvmeof-pytest-base
    entrypoint: |
      python3 -m pytest tests/test_multi_gateway.py

  ceph-nvmeof-pytest-state:
    extends:
      service: ceph-nvmeof-pytest-base
    entrypoint: |
      python3 -m pytest tests/test_state.py

  ceph-nvmeof-devel:
    # Runs from source code in current dir
    extends:
      service: ceph-nvmeof-base
    depends_on:
      ceph-cluster:
        condition: service_healthy
    volumes:
      - .:/src
  ceph-nvmeof-cli:
    image: ceph-nvmeof-cli
    build:
      context: .
      target: ceph-nvmeof-cli
volumes:
  ceph-conf:
